package edu.pitt.cs;

// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
import java.time.Duration;

import static org.hamcrest.MatcherAssert.assertThat;

public class PittEduTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;

  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
    
    driver.manage().timeouts().implicitlyWait(Duration.ofSeconds(30));
    driver.manage().window().setSize(new Dimension(1200, 800));
  }

  @After
  public void tearDown() {
    driver.quit();
  }

  @Test
  public void tEST1TITLE() {
    driver.get("https://www.pitt.edu//");
    assertThat(driver.getTitle(), is("Home | University of Pittsburgh"));
  }

  @Test
  public void tEST2LOGOEXISTS() {
    driver.get("https://www.pitt.edu//");
    {
      List<WebElement> elements = driver.findElements(By.xpath("//img[@alt=\'University of Pittsburgh\']"));
      assert(elements.size() > 0);
    }
  }

  @Test
  public void tEST3LOGOIMAGE() {
    driver.get("https://www.pitt.edu//");
    {                                                   // *[@id="block-pitt-default-sitebranding"]/div/a/img
      WebElement element = driver.findElement(By.xpath("//div[@id=\'block-pitt-default-sitebranding\']/div/a/img"));
      String attribute = element.getAttribute("src");
      vars.put("logoSrc", attribute);
    }
    assertTrue(vars.get("logoSrc").toString().contains("/themes/custom/pitt_default/logo.svg"));

  }

  @Test
  public void tEST4SCHOOLSSCI() {
    driver.get("https://www.pitt.edu/");

    // Click on the hamburger menu to expand it
    driver.findElement(By.cssSelector(".icon-hamburger")).click();

    // Wait for the parent element containing the list of items to become visible
    WebDriverWait wait = new WebDriverWait(driver, Duration.ofSeconds(30));
    wait.until(ExpectedConditions.visibilityOfElementLocated(By.id("block-collegesschools-menu")));

    // Locate the third item in the list and verify its text
    WebElement menuItem = driver.findElement(By.xpath("//*[@id='menu-blockquick-links-3']/ul/li[3]/a"));
    String actualText = menuItem.getText();

    // Assert that the text of the third item matches the expected text
    assertEquals("Computing & Information", actualText.trim());
  }

  @Test
  public void tEST5SCHOOLSCOUNT() {
    driver.get("https://www.pitt.edu/");
    driver.manage().window().setSize(new Dimension(1680, 1050));
    driver.findElement(By.cssSelector(".icon-hamburger")).click();
    {
      List<WebElement> elements = driver.findElements(By.xpath("//div[@id=\'menu-blockquick-links-3\']/ul"));
      assert(elements.size() > 0);
    }
  }

  @Test
  public void tEST6SEARCHCSC() {
    driver.get("https://www.pitt.edu/");
    driver.manage().window().setSize(new Dimension(1680, 1050));
    driver.findElement(By.cssSelector(".navigation-button-wrapper")).click();
    driver.findElement(By.cssSelector(".icon-search")).click();
    {
      WebElement element = driver.findElement(By.cssSelector(".icon-search"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    driver.findElement(By.id("gsc-i-id1")).click();
    driver.findElement(By.id("gsc-i-id1")).sendKeys("csc");
    driver.findElement(By.id("gsc-i-id1")).sendKeys(Keys.ENTER);
    assertThat(driver.findElement(By.linkText("Computer Science Club (CSC) | Department of Computer Science ...")).getText(), is("Computer Science Club (CSC) | Department of Computer Science ..."));
  }
}